### ISSUE TITLE
I still can't run your project

### ISSUE THREAD

**Issue by magicwutong** [ssg-research/WAFFLE#2]
Thank you very much for noticing my problem and helping me in time. There is no doubt that this is a great project,at the same time, I also read your paper carefully but I still can't run it locally. The project seems to have a lot of grammatical problems. Have you forgotten to upload the latest modified version? I would be very grateful if there is one
<img width="741" alt="bug" src="https://user-images.githubusercontent.com/87414138/139839453-5fcf315e-9c8d-47ba-bc61-45a97ad5d5cf.png">

**Comment by paranoid-27** [comment]
Have you ever encountered this problem? It seems that the configuration file is missing：

Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/home/ym/anaconda3/envs/pysyft/lib/python3.7/site-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.13.0-rc1.so'
[DEFAULT]
Traceback (most recent call last):
  File "/home/ym/WAFFLE-main/src/main.py", line 152, in <module>
    main(config, args.experiment, args.generate_watermark, args.patching_type)
  File "/home/ym/WAFFLE-main/src/main.py", line 20, in main
    env = datapre.prepare_data(config)
  File "/home/ym/WAFFLE-main/src/datapre.py", line 23, in prepare_data
    model_save_path = config["DEFAULT"]["model_save_path"]
  File "/home/ym/anaconda3/envs/pysyft/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'model_save_path'


code in main.py:
    parser.add_argument(
        "--config_file",
        type=str,
        default="./configurations/mnist-to-pattern-ws100-l5-100c-P-R1.ini",
        help="Configuration file for the experiment.")

**Comment by magicwutong** [comment]
The author re-uploaded the configuration file, you can re-download the project and run it.

**Comment by bussfromspace** [comment]
Hi,
@yangmingdashuaige , I uploaded configuration files. You have to pass a configuration file as an argument (you can check README for how to replicate experiments) in order to successfully run it. In ynl file, I had a tensorflow version that was not supported any longer but I have set it to 1.3.1 now. If you pull the repo again and re-generate the conda env, you can also get rid of "falling back to insecure randomness" error. 

@magicwutong, I tested the code from scratch and works without any problem in my setup. I assume the problem is with the PySyft installation. Could you also pull the repo again for the updated yml file? What are your current Python, torch, PySyft versions?

**Comment by sebszyller** [comment]
I'm closing this because it's stale.
